### ISSUE TITLE
사냥꾼 직업구현

### ISSUE THREAD

**Issue by zhunhe** [goyohangoyoill/ONUWF#17]

**Comment by zhunhe** [comment]
@seojaeinblank User 구조체에 voteUserId 추가했어요. 유저별로 누가 누구한테 투표했는지 uid 값으로 저장하는 변수에요. 혹시나 필요하시면 쓰세요 ~

**Comment by seojaeinblank** [comment]
감사합니당 ~


2021년 7월 17일 (토) 오전 3:54, zhunhe ***@***.***>님이 작성:
