### ISSUE TITLE
입장 퇴장 / 직업추가

### ISSUE THREAD

**Issue by guny524** [goyohangoyoill/ONUWF#2]

**Comment by guny524** [comment]
메인에 머지 했고 빌드 가능하고
발견된 버그 고쳐서 메인에서 실행 가능합니다

**Comment by guny524** [comment]
7946fc5777e1f799895bd73146b813e131c94f51

**Comment by zhunhe** [comment]
@guny524 "ㅁ시작" 후 직업추가에서 "<" 하면 터지고 마지막에서 ">" 하면 터져용

**Comment by guny524** [comment]
오호 확인했습니다 고칠게요...

**Comment by guny524** [comment]
babcd58748c801bce072373a18771a9cb638e82a
위 커밋에서 고쳤어요~

**Comment by zhunhe** [comment]
넵 !!
